version: "3.4"

services:
  storefront:
    image: storefront
    container_name: storefront
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL}
        NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL}
    restart: always
    ports:
      - 3000:3000
    networks:
      - saleor-bridge-network

  # Add more containers below (nginx, postgres, etc.)

networks:
  saleor-bridge-network:
    driver: bridge